
PROC IML;
* DEFINE THE MATRIX WHICH IS A IN THIS CASE;
	A={1 0 1,
	   0 2 2,
	   1 2 3};
RANKOFMATRIX =ROUND(TRACE(GINV(A)*A)); *GETTING THE RANK OF THE MATRIX;
DETERMI = DET(A); * DETERMINANT OF MATRIX A;
EVECTOR = EIGVEC(A); *GETTING THE EIGEN VECTOR;
EVALUE = EIGVAL(A);   *GETTING THE EIGEN VALUE;
INVEVECTOR = INV(EVECTOR); *GETTING THE INVERSE OF THE EIGENVECTOR;
DIAGONALEVALUE = DIAG(EVALUE); *CONVERTING THE EIGEN VALUE TO DIAGONAL MATRIX;
ORIGINALMATRIX = EVECTOR * DIAGONALEVALUE * INVEVECTOR; *TESTING THE LEMMA 2(IV) IN THE TEXTBOOK;
PRINT RANKOFMATRIX DETERMI EVALUE EVECTOR INVEVECTOR DIAGONALEVALUE ORIGINALMATRIX;
QUIT;



